t=int(input("Enter your salary:"))
a=int(input("Enter the shopping bill number1:"))
b=int(input("Enter the shopping bill number2:"))
c=int(input("Enter the shopping bill number3:"))
print(f"Total salary spent on shopping:{a+b+c}")
print(f"The percentage of the salary spent on shopping is:{(a+b+c)*100/t}")